import Head from "next/head";
import styles from "@/styles/page.module.scss";
import { HeaderContainer } from "@/pages/login/containers/header";
import { FormContainer } from "@/pages/login/containers/form";
import { ActionContainer } from "@/pages/login/containers/action";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login - Spotify</title>
        <meta name="description" content="Generated by Login - Spotify" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeaderContainer />
        <FormContainer />
        <ActionContainer />
      </main>
    </>
  );
}
