import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";
import { ButtonComponent } from "@/components/button";
import styles from "@/styles/home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Link href="/login">
            <ButtonComponent label="LOGIN" />
          </Link>
        </div>
      </main>
    </>
  );
}
